export const actionTypes = {
    /* user actions */
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
    USER_LOGOUT: "USER_LOGOUT",
    /* casetype actions */
    CASETYPES_GET: "CASETYPES_GET",
    /* case actions */
    CASES_POST_SUCCESS: "CASES_POST_SUCCESS",
    CASES_POST_FAIL: "CASES_POST_FAIL",
    CASES_GET_SUCCESS: "CASES_GET_SUCCESS",
    CASES_GET_FAIL: "CASES_GET_FAIL",
    CASES_GET_BYID_SUCCESS: "CASES_GET_BYID_SUCCESS",
    CASES_GET_BYID_FAIL: "CASES_GET_BYID_FAIL",
    CASES_GETPAGE_BYID_SUCESS: "CASES_GETPAGE_BYID_SUCESS",
    CASES_GETPAGE_BYID_FAIL: "CASES_GETPAGE_BYID_FAIL",
    /* assignment actions */
    ASSIGNMENTS_GET_SUCCESS: "ASSIGNMENTS_GET_SUCCESS",
    ASSIGNMENTS_GET_FAIL: "ASSIGNMENTS_GET_FAIL",
    ASSIGNMENTS_GETBYID_SUCCESS: "ASSIGNMENTS_GETBYID_SUCCESS",
    ASSIGNMENTS_GETBYID_FAIL: "ASSIGNMENTS_GETBYID_FAIL",
    ASSIGNMENTS_POST_BYID_SUCCESS: "ASSIGNMENTS_POST_BYID_SUCCESS",
    ASSIGNMENTS_POST_BYID_FAIL: "ASSIGNMENTS_POST_BYID_FAIL",
    ASSIGNMENTS_PUT_BYID_SUCCESS: "ASSIGNMENTS_PUT_BYID_SUCCESS",
    ASSIGNMENTS_PUT_BYID_FAIL: "ASSIGNMENTS_PUT_BYID_FAIL",
    ASSIGNMENTS_RESET: "ASSIGNMENTS_RESET",
    ASSIGNMENTS_RESET_ACTIONSTATUS: "ASSIGNMENTS_RESET_ACTIONSTATUS",
    ASSIGNMENTS_GETACTION_BYID_SUCCESS: "ASSIGNMENTS_GETACTION_BYID_SUCCESS",
    ASSIGNMENTS_GETACTION_BYID_FAIL: "ASSIGNMENTS_GETACTION_BYID_FAIL",
    /* datapage actions */
    DATATYPE_GET_BYID_SUCCESS: "DATATYPE_GET_BYID_SUCCESS",
    DATATYPE_GET_BYID_FAIL: "DATATYPE_GET_BYID_FAIL"
}